name: fastib2pci
on:
  push:
    branches:
      - main
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
          
      - name: checkout pages
        uses: actions/checkout@v3
        with: 
            ref: 'gh-pages'
            path: 'public'
            
      - name: checkout pci
        run: git clone https://gitlab.tba-hosting.de/fwagner/oat-ibtaoconnector.git ./pci
            
      - name: checkout items
        uses: actions/checkout@v3
        with: 
            path: 'items'
            
      - name: build pci
        run: |
           export REPONAME="${GITHUB_REPOSITORY#*/}"
           firstitem=$(ls items | grep -e ".zip" | head -1)
           ls items
           cd ./pci/scripts/packer
           npm i
           echo $firstitem
           echo "https://$GITHUB_REPOSITORY_OWNER.github.io/$REPONAME"
           node ./index.js -u "https://$GITHUB_REPOSITORY_OWNER.github.io/$REPONAME" -i "../../../items/$firstitem" -o "../../../public/ibTaoConnector.zip"
             
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: public
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
            
 
      
